---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

## Loading and preprocessing the data
    ###In this preprocessing step, working directory was set, data was unzipped and lattice package 
    is being utilized
```{r}
getwd()
setwd("C:/Users/Suresh/RepData_PeerAssessment1")
activity <- read.csv("activity.csv", colClasses = c("numeric", "character", "numeric"))
head(activity)
names(activity)
library(lattice)
activity$date <- as.Date(activity$date, "%Y-%m-%d")

```



## What is mean total number of steps taken per day?
```{r}
StepsTotal <- aggregate(steps ~ date, data = activity, sum, na.rm = TRUE)
hist(StepsTotal$steps, main = "Total steps by day", xlab = "day", col = "green")
mean(StepsTotal$steps)
median(StepsTotal$steps)

```



## What is the average daily activity pattern?
```{r}
time_series <- tapply(activity$steps, activity$interval, mean, na.rm = TRUE)
plot(row.names(time_series), time_series, type = "l", xlab = "5-min interval", 
     ylab = "Avg. across all Days", main = "Avg. number of steps taken", 
     col = "magenta")
max_interval <- which.max(time_series)
names(max_interval)

```



## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
